#!/usr/bin/env python3
"""Generate the deterministic gzip dashboard header embedded in ESP32 flash."""

from __future__ import annotations

import argparse
import struct
import zlib
from pathlib import Path


FIRMWARE_ROOT = Path(__file__).resolve().parents[1]
SOURCE = FIRMWARE_ROOT / "web" / "index.html"
TARGET = FIRMWARE_ROOT / "include" / "dashboard_page.generated.h"


def deterministic_gzip(data: bytes) -> bytes:
    compressor = zlib.compressobj(level=9, method=zlib.DEFLATED, wbits=-15)
    payload = compressor.compress(data) + compressor.flush()
    header = b"\x1f\x8b\x08\x00\x00\x00\x00\x00\x02\xff"
    trailer = struct.pack("<II", zlib.crc32(data) & 0xFFFFFFFF, len(data) & 0xFFFFFFFF)
    return header + payload + trailer


def render_header(data: bytes) -> str:
    compressed = deterministic_gzip(data)
    rows = []
    for offset in range(0, len(compressed), 16):
        chunk = compressed[offset : offset + 16]
        rows.append("    " + ", ".join(f"0x{byte:02x}" for byte in chunk) + ",")
    byte_rows = "\n".join(rows)
    return f"""// Generated by firmware/scripts/generate_dashboard_header.py. Do not edit.
#pragma once

#include <Arduino.h>
#include <cstddef>
#include <cstdint>

namespace watering {{

static const uint8_t kDashboardHtmlGzip[] PROGMEM = {{
{byte_rows}
}};
constexpr std::size_t kDashboardHtmlGzipLength = sizeof(kDashboardHtmlGzip);
constexpr std::size_t kDashboardHtmlSourceLength = {len(data)}U;

}}  // namespace watering
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if the generated header is stale")
    arguments = parser.parse_args()

    expected = render_header(SOURCE.read_bytes())
    current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
    if arguments.check:
        if current != expected:
            print("dashboard header is missing or stale; run firmware/scripts/generate_dashboard_header.py")
            return 1
        return 0

    TARGET.write_text(expected, encoding="utf-8", newline="\n")
    print(f"generated {TARGET.relative_to(FIRMWARE_ROOT.parent)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
